---
title: "VP timing, dosage, infection"
output:
  html_document
---

Report generated at: `r format(as.POSIXct(Sys.time(), format = "%y%m%d %H:%M"), "%m/%d/%Y %I:%M %p")` PDT

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(gridExtra)
library(plotly)
library(ggbeeswarm)
library(viridis)
library(ggpubr)
library(cowplot)
library(grid)


knitr::opts_chunk$set(
  echo = FALSE,
  dev = c("svg")
)
source("./lib/readers.R", chdir = TRUE)
source("./lib/datatables.R", chdir = TRUE)

TABLEDIR = normalizePath(sprintf('%s/../report_tables', .getpwd()))
```

```{r constants, include=FALSE}

PRE_OMICRON = c(
  "Alpha",
  "Beta",
  "Gamma",
  "Delta",
  "BA.1"
)

OMICRON = c(
  "BA.1",
  "BA.2",
  "BA.2.12.1",
  "BA.2.75",
  "BA.2.75.2",
  "XBB",
  "BA.4/5",
  "BA.4.6",
  "BQ.1",
  "BQ.1.1",
  "BF.7"
)

VACCINES = c(
  "BNT162b2",
  'mRNA-1273',
  'AZD1222',
  'Ad26.COV2.S',
  'BBV152',
  'CoronaVac',
  'BBIBP-CorV',
  'Sputnik V'
  # 'NVX-CoV2373',
  # 'MVC-COV1901',
  # 'ZF2001'
)

VACCINE_META = c(
  "BNT162b2"= "BNT162b2\n(BioNTech)",
  'mRNA-1273' = 'mRNA-1273\n(Moderna)',
  'AZD1222' = "AZD1222\n(AstraZeneca)",
  'Ad26.COV2.S' = "Ad26.COV2.S\n(Janssen Vaccines)",
  'BBV152' = "BBV152\n(Bharat Biotech)",
  'CoronaVac' = "CoronaVac\n(Sinovac Biotech)",
  'BBIBP-CorV' = "BBIBP-CorV\n(Sinopharm Beijing)",
  'Sputnik V' = "Sputnik V\n(Gamaleya)"
  # 'NVX-CoV2373',
  # 'MVC-COV1901',
  # 'ZF2001'
)

TITER_LEVEL = c("high", "middle", "low")
# TITER_LEVEL = c("low", "middle", "high")

```

```{r tables}
df_nt = read.dbTable(
    'figure/figure_plasma_variant_titer.csv', tables_dir=TABLEDIR) %>%
  mutate(level=ifelse(
    titer <= 40, 'low',
    ifelse(titer > 40 & titer <= 100,
           'middle', 'high'))) %>%
  mutate(level = factor(level, TITER_LEVEL)) %>%
  mutate(var_name = ifelse(startsWith(var_name, 'Omicron'), substring(var_name, 9), var_name))

# print(unique(df_nt$var_name))

df_nt_pre_omi = df_nt %>%
  filter(var_name %in% PRE_OMICRON) %>%
  mutate(
    var_name = factor(var_name, PRE_OMICRON),
  )

df_nt_omi = df_nt %>%
  filter(var_name %in% OMICRON) %>%
  mutate(
    var_name = factor(var_name, OMICRON),
  )
```

```{r functions, include=FALSE}

LINE_WIDTH = 3

draw_blank <- function() {
  dfPlot = data.frame()
  p <- ggplot(dfPlot) +
    geom_blank() +
    theme(
      legend.position = "none",
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      plot.title = element_blank(),
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
    )
  p
}

draw_sub_plot <- function(dfPlot, figLabel, x_labels) {

  dfAgg = dfPlot %>%
    group_by(var_name, level) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name))

  dfAggRef = dfPlot %>%
    group_by(var_name) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name)) %>%
    mutate(
      label=ifelse(
        num_ref_name > 0,
        sprintf('%s', num_ref_name),
        ''
      )
    )


  # dfAgg = dfPlot %>%
  #   group_by(var_name, level) %>%
  #   summarise(num_results=sum(num_exp)) %>%
  #   mutate(
  #     label = ifelse(
  #       num_study > 0,
  #       yes=sprintf('%s', num_study),
  #       no=''
  #     )
  #   )
  # mutate(
  #   label = ifelse(
  #     num_study > 1,
  #     yes=sprintf('%s studies\n%s results', num_study, num_results),
  #     no=ifelse(
  #       num_study > 0,
  #       yes=sprintf('%s study\n%s results', num_study, num_results),
  #       no=''
  #     )
  #   )
  # )

  if (dim(dfAgg)[1] == 0) {
    p <- draw_blank()
    return(p)
  }

  max_y = max(dfAggRef$num_exp)
  if (max_y < 100 ) {
    max_y = 100
  }

  p <- ggplot(data=dfAgg, aes(x=var_name, y=num_exp)) +
    geom_bar(
      aes(fill=level),
      size=0.2,
      color="#000000",
      stat="identity",
      position='stack'
    ) +
    scale_fill_manual(
      values = c(
        'low' = "#a82f14",
        'middle' = "#ee8e7f",
        'high' = "#ffffff"
      ),
      name="Neutralization titer",
      breaks=TITER_LEVEL,
      labels=c(
        'high' = ">100",
        'middle' = "40~100",
        'low' = "<=40"
      )
    ) +
    scale_x_discrete(
      limits=x_labels
    ) +
    scale_y_continuous(
      expand=expansion(mult = c(0, .2)),
      # breaks=c(1, 500, 1000, 2000),
      breaks=pretty_breaks(),
      limits=c(0, max_y)
    ) +
    geom_text(
      data=dfAggRef,
      aes(y=num_exp, label=label),
      size = 8,
      vjust = -0.2
    ) +
    theme(
      legend.position = "none",
      # legend.title = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_text(size=25, angle=90),
      plot.title = element_text(hjust = 0.5, size=12),
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = 'black'),
      plot.margin = margin(t=0, l=10, r=10, b=10)
    )

  p = p + annotate(
    "text",
    y= Inf,
    x = Inf,
    label=figLabel,
    size=7,
    vjust=1.1,
    hjust=1.1)
  p
}

draw_panel <- function(df) {
  plots = list()
  i = 1
  num_graph = length(VACCINES)

  for (vacc in VACCINES) {
    dfPlot = df %>%
      filter(vaccine_name == vacc)

      p = draw_sub_plot(dfPlot, vacc)

      if (i %% LINE_WIDTH == 1) {
        p = p + theme(
          axis.title.y = element_text(size=25, face="bold", colour = "black"),
        ) +
          ylab("# Results")
      }

      if (i > num_graph - LINE_WIDTH) {
        p = p + theme(
          axis.title.x = element_blank(),
          axis.text.x = element_text(size=24, angle=90, hjust=1),
          # axis.text.x = element_text(size=35),
        )
      }

      plots[[i]] = p
      i = i + 1

  }
  plots
}

add_x_labels <- function(p) {
  p = p + theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(size=24, angle=90, hjust=1),
      # axis.text.x = element_text(size=35),
    )
}

adjust_plot_axis <- function(p, num_graph, i) {
  if (i %% LINE_WIDTH == 1) {
    p = p + theme(
      axis.title.y = element_text(size=25, face="bold", colour = "black"),
    ) +
      ylab("# Results")
  }

  if (i > num_graph - LINE_WIDTH) {
    p = add_x_labels(p)
  }
  p
}

is_blank_figure <- function(dfPlot) {
  dfAgg = dfPlot %>%
    group_by(var_name, level) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name))

  dfAggRef = dfPlot %>%
    group_by(var_name) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name)) %>%
    mutate(
      label=ifelse(
        num_ref_name > 0,
        sprintf('%s', num_ref_name),
        ''
      )
    )

  if (dim(dfAgg)[1] == 0) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}

draw_panel_groups <- function(df, x_labels) {
  plots = list()
  i = 1
  num_graph = length(VACCINES)
  last_in_column = list()

  for (vacc in VACCINES) {
    dfPlot = df %>%
      filter(vaccine_name == vacc)

    if (dim(dfPlot)[1] == 0) {
      num_graph = num_graph - 3
      next
    }

    dfPlot_by_month = dfPlot %>% filter(month==1)
    figTitle = paste(VACCINE_META[vacc], '1M', sep=' ')
    p = draw_sub_plot(dfPlot_by_month, figTitle, x_labels)
    p = adjust_plot_axis(p, num_graph * 3, i)
    plots[[i]] = p
    if (!is_blank_figure(dfPlot_by_month)) {
      last_in_column[1] = i
    }
    i = i + 1

    dfPlot_by_month = dfPlot %>% filter(month>1 & month <= 6)
    figTitle = paste(VACCINE_META[vacc], '2-6M', sep=' ')
    p = draw_sub_plot(dfPlot_by_month, figTitle, x_labels)
    p = adjust_plot_axis(p, num_graph * 3, i)
    plots[[i]] = p
    if (!is_blank_figure(dfPlot_by_month)) {
      last_in_column[2] = i
    }
    i = i + 1

    dfPlot_by_month = dfPlot %>% filter(month>6)
    figTitle = paste(VACCINE_META[vacc], '>6M', sep=' ')
    p = draw_sub_plot(dfPlot_by_month, figTitle, x_labels)
    p = adjust_plot_axis(p, num_graph * 3, i)
    plots[[i]] = p
    if (!is_blank_figure(dfPlot_by_month)) {
      last_in_column[3] = i
    }
    i = i + 1
  }

  for (index in last_in_column) {
    if (index < max(unlist(last_in_column))) {
      next
    }
    plots[[index]] = add_x_labels(plots[[index]])
  }

  p = draw_sub_plot(df, '', x_labels) + theme(
      legend.position = "bottom",
      legend.key.size = unit(1, 'cm'),
      legend.text = element_text(size=14),
      legend.title = element_text(size=14)
    )

  legend = get_legend(p)
  plots[[i]] = legend

  plots
}

show_panel <- function(plots) {
  lines = (length(plots) %/% LINE_WIDTH) - 1
  print(lines)
  heights_ratios = rep(1, lines)
  heights_ratios[length(heights_ratios) + 1] = 1.2
  heights_ratios[length(heights_ratios) + 1] = 0.1
  
  grid.arrange(grobs = plots, ncol=LINE_WIDTH, heights=heights_ratios)
}
```

## Figures {.tabset}

### Pre Omicron, No history of infection, 2 or more shots

```{r nt-pre-omi-vac-2shot, fig.height=80, fig.retina=4, fig.width=18, message=FALSE, warning=FALSE, echo=FALSE}

df_draw = df_nt_pre_omi %>%
  filter(dosage>=2) %>%
  filter(infection=='')

plots = draw_panel_groups(df_draw, PRE_OMICRON)

show_panel(plots)
```

### Omicron, No history of infection, 2 or more shots

```{r nt-omi-vac-2ormore, fig.height=80, fig.retina=4, fig.width=18, message=FALSE, warning=FALSE, echo=FALSE}

df_draw = df_nt_omi %>%
  filter(dosage>=2) %>%
  filter(infection=='')

plots = draw_panel_groups(df_draw, OMICRON)

show_panel(plots)
```

### Pre-Omicron, history of infection, 2 or more shots

```{r nt-pre-omi-inf-vac-2ormore, fig.height=40, fig.retina=4, fig.width=18, message=FALSE, warning=FALSE, echo=FALSE}

df = df_nt_pre_omi %>%
  filter(dosage>=2) %>%
  filter(infection !='') %>%
  filter(!(vaccine_name %in% c('BBV152', 'Sputnik V')))

plots = draw_panel_groups(df, PRE_OMICRON)

show_panel(plots)
```

### Omicron, history of infection, 2 or more shots

```{r nt-omi-inf-vac-2ormore, fig.height=40, fig.retina=4, fig.width=18, message=FALSE, warning=FALSE, echo=FALSE}

df = df_nt_omi %>%
  filter(dosage>=2) %>%
  filter(infection !='') %>%
  filter(!(vaccine_name %in% c('BBV152', 'Sputnik V')))

plots = draw_panel_groups(df, OMICRON)

show_panel(plots)
```
