---
title: "VP timing, dosage, infection"
output:
  html_document
---

Report generated at: `r format(as.POSIXct(Sys.time(), format = "%y%m%d %H:%M"), "%m/%d/%Y %I:%M %p")` PDT

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(gridExtra)
library(plotly)
library(ggbeeswarm)
library(viridis)
library(ggpubr)
library(cowplot)
library(grid)


knitr::opts_chunk$set(
  echo = FALSE,
  dev = c("svg")
)
source("./lib/readers.R", chdir = TRUE)
source("./lib/datatables.R", chdir = TRUE)

TABLEDIR = normalizePath(sprintf('%s/report_tables', .getpwd()))

VARIANT = c(
  "Alpha",
  "Beta",
  "Gamma",
  "Delta",
  "Omicron/BA.1",
  "Omicron/BA.2",
  "Omicron/BA.5",
  'Omicron/BA.4/5',
  "Omicron/BA.2.75"
)

VARIANT_GREEK = c(
  "Alpha" = 'α',
  "Beta" = 'β',
  "Gamma" = 'γ',
  "Delta" = 'δ',
  "Omicron/BA.1" = 'ο/BA.1',
  "Omicron/BA.2" = 'ο/BA.2',
  "Omicron/BA.4/5" = 'ο/BA.4/5',
  "Omicron/BA.2.75" = 'ο/BA.2.75'
)

RX_NAME_LIST = c(
  "BNT162b2",
  'mRNA-1273',
  'AZD1222',
  'Ad26.COV2.S',
  # 'NVX-CoV2373',
  'BBV152',
  'CoronaVac',
  'BBIBP-CorV',
  'Sputnik V'
  # 'MVC-COV1901',
  # 'ZF2001'
)

RX_NAME_COMP_LIST = c(
  "BNT162b2"= "BNT162b2\n(BioNTech)",
  'mRNA-1273' = 'mRNA-1273\n(Moderna)',
  'AZD1222' = "AZD1222\n(AstraZeneca)",
  'Ad26.COV2.S' = "Ad26.COV2.S\n(Janssen Vaccines)",
  # 'NVX-CoV2373',
  'BBV152' = "BBV152\n(Bharat Biotech)",
  'CoronaVac' = "CoronaVac\n(Sinovac Biotech)",
  'BBIBP-CorV' = "BBIBP-CorV\n(Sinopharm Beijing)",
  'Sputnik V' = "Sputnik V\n(Gamaleya)"
  # 'MVC-COV1901',
  # 'ZF2001'
)

RX_NAME_COLOR = c(
  "CP" = "#f44336",
  "BNT162b2" = "#3a96f3",
  'mRNA-1273' = "#a946bb",
  'AZD1222' = "#f7c10a",
  'Ad26.COV2.S' = "#f05723",
  # 'NVX-CoV2373',
  'BBV152' = "#795548",
  'CoronaVac' = "#4caf50",
  'BBIBP-CorV' = "#e91e63",
  'Sputnik V' = "#607d8b"
  # 'MVC-COV1901',
  # 'ZF2001'
)
# TITER_LEVEL = c("low", "middle", "high")
TITER_LEVEL = c("high", "middle", "low")

LINE_WIDTH = 3

df_titer = read.dbTable('figure/figure_plasma_variant_titer.csv', tables_dir=TABLEDIR) %>%
  mutate(level=ifelse(titer <= 40, 'low', ifelse(titer > 40 & titer <= 100, 'middle', 'high'))) %>%
  mutate(
    var_name = factor(var_name, VARIANT),
    level = factor(level, TITER_LEVEL)
  )
```

```{r functions, include=FALSE}
draw_blank <- function() {
  dfPlot = data.frame()
  p <- ggplot(dfPlot) +
    geom_blank() +
    theme(
      legend.position = "none",
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      plot.title = element_blank(),
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
    )
  p
}

draw_titer <- function(dfPlot, figLabel) {

  dfAgg = dfPlot %>%
    group_by(var_name, level) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name))

  dfAggRef = dfPlot %>%
    group_by(var_name) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name)) %>%
    mutate(
      label=ifelse(
        num_ref_name > 0,
        sprintf('%s', num_ref_name),
        ''
      )
    )


  # dfAgg = dfPlot %>%
  #   group_by(var_name, level) %>%
  #   summarise(num_results=sum(num_exp)) %>%
  #   mutate(
  #     label = ifelse(
  #       num_study > 0,
  #       yes=sprintf('%s', num_study),
  #       no=''
  #     )
  #   )
    # mutate(
    #   label = ifelse(
    #     num_study > 1,
    #     yes=sprintf('%s studies\n%s results', num_study, num_results),
    #     no=ifelse(
    #       num_study > 0,
    #       yes=sprintf('%s study\n%s results', num_study, num_results),
    #       no=''
    #     )
    #   )
    # )

  if (dim(dfAgg)[1] == 0) {
    p <- draw_blank()
    return(p)
  }

  max_y = max(dfAggRef$num_exp)
  if (max_y < 100 ) {
    max_y = 100
  }


  p <- ggplot(data=dfAgg, aes(x=var_name, y=num_exp)) +
    geom_bar(
      aes(fill=level),
      size=0.2,
      color="#000000",
      stat="identity",
      position='stack'
    ) +
    scale_fill_manual(
      values = c(
        'low' = "#a82f14",
        'middle' = "#ee8e7f",
        'high' = "#ffffff"
      ),
      name="Neutralization titer",
      breaks=TITER_LEVEL,
      labels=c(
        'high' = ">100",
        'middle' = "40~100",
        'low' = "<=40"
      )
    ) +
    scale_x_discrete(
      labels=VARIANT_GREEK,
      limits=VARIANT
    ) +
    scale_y_continuous(
      expand=expansion(mult = c(0, .2)),
      # breaks=c(1, 500, 1000, 2000),
      breaks=pretty_breaks(),
      limits=c(0, max_y)
    ) +
    geom_text(
      data=dfAggRef,
      aes(y=num_exp, label=label),
      size = 8,
      vjust = -0.2
    ) +
    theme(
      legend.position = "none",
      # legend.title = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_text(size=25, angle=90),
      plot.title = element_text(hjust = 0.5, size=12),
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = 'black'),
      plot.margin = margin(t=0, l=10, r=10, b=10)
    )

  p = p + annotate(
    "text",
    y= Inf,
    x = Inf,
    label=figLabel,
    size=7,
    vjust=1.1,
    hjust=1.1)
  p
}

draw_panel <- function(df) {
  plots = list()
  i = 1
  num_graph = length(RX_NAME_LIST)

  for (vacc in RX_NAME_LIST) {
    dfPlot = df %>%
      filter(vaccine_name == vacc) %>%
      mutate(
        var_name = factor(var_name, VARIANT),
        level = factor(level, TITER_LEVEL)
      )

      p = draw_titer(dfPlot, vacc)

      if (i %% LINE_WIDTH == 1) {
        p = p + theme(
          axis.title.y = element_text(size=25, face="bold", colour = "black"),
        ) +
          ylab("# Results")
      }

      if (i > num_graph - LINE_WIDTH) {
        p = p + theme(
          axis.title.x = element_blank(),
          axis.text.x = element_text(size=24, angle=90, hjust=1),
          # axis.text.x = element_text(size=35),
        )
      }

      plots[[i]] = p
      i = i + 1

  }
  plots
}

add_x_labels <- function(p) {
  p = p + theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(size=24, angle=90, hjust=1),
      # axis.text.x = element_text(size=35),
    )
}

adjust_plot_axis <- function(p, num_graph, i) {
  if (i %% LINE_WIDTH == 1) {
    p = p + theme(
      axis.title.y = element_text(size=25, face="bold", colour = "black"),
    ) +
      ylab("# Results")
  }

  if (i > num_graph - LINE_WIDTH) {
    p = add_x_labels(p)
  }
  p
}

is_blank_figure <- function(dfPlot) {
  dfAgg = dfPlot %>%
    group_by(var_name, level) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name))

  dfAggRef = dfPlot %>%
    group_by(var_name) %>%
    summarize(num_exp=sum(num_exp), num_ref_name = n_distinct(ref_name)) %>%
    mutate(
      label=ifelse(
        num_ref_name > 0,
        sprintf('%s', num_ref_name),
        ''
      )
    )

  if (dim(dfAgg)[1] == 0) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}

draw_panel_groups <- function(df) {
  plots = list()
  i = 1
  num_graph = length(RX_NAME_LIST)
  last_in_column = list()

  for (vacc in RX_NAME_LIST) {
    dfPlot = df %>%
      filter(vaccine_name == vacc)

    if (dim(dfPlot)[1] == 0) {
      num_graph = num_graph - 3
      next
    }

    dfPlot2 = dfPlot %>% filter(month==1)
    figLabel = paste(RX_NAME_COMP_LIST[vacc], '1M', sep=' ')
    p = draw_titer(dfPlot2, figLabel)
    p = adjust_plot_axis(p, num_graph * 3, i)
    plots[[i]] = p
    if (!is_blank_figure(dfPlot2)) {
      last_in_column[1] = i
    }
    i = i + 1

    dfPlot2 = dfPlot %>% filter(month>1 & month <= 6)
    figLabel = paste(RX_NAME_COMP_LIST[vacc], '2-6M', sep=' ')
    p = draw_titer(dfPlot2, figLabel)
    p = adjust_plot_axis(p, num_graph * 3, i)
    plots[[i]] = p
    if (!is_blank_figure(dfPlot2)) {
      last_in_column[2] = i
    }
    i = i + 1

    dfPlot2 = dfPlot %>% filter(month>6)
    figLabel = paste(RX_NAME_COMP_LIST[vacc], '>6M', sep=' ')
    p = draw_titer(dfPlot2, figLabel)
    p = adjust_plot_axis(p, num_graph * 3, i)
    plots[[i]] = p
    if (!is_blank_figure(dfPlot2)) {
      last_in_column[3] = i
    }
    i = i + 1
  }

  for (index in last_in_column) {
    if (index < max(unlist(last_in_column))) {
      next
    }
    plots[[index]] = add_x_labels(plots[[index]])
  }

  p = draw_titer(df, figLabel) + theme(
      legend.position = "bottom",
      legend.key.size = unit(1, 'cm'),
      legend.text = element_text(size=14),
      legend.title = element_text(size=14)
    )

  legend = get_legend(p)
  plots[[i]] = legend

  plots
}
```

## Figures  {.tabset}

### Titer, No history of infection, 2 shots

```{r titer-noinf-2shots, fig.height=64, fig.retina=4, fig.width=18, message=FALSE, warning=FALSE, echo=FALSE}

df = df_titer %>%
  filter(dosage==2) %>%
  filter(infection=='') %>%
  filter(var_name %in% VARIANT)

plots = draw_panel_groups(df)

lines = (length(plots) %/% LINE_WIDTH) - 1
heights_ratios = rep(1, lines)
heights_ratios[length(heights_ratios) + 1] = 1.2
heights_ratios[length(heights_ratios) + 1] = 0.1

grid.arrange(grobs = plots, ncol=LINE_WIDTH, heights=heights_ratios)
```


### Titer, No history of infection, 3 shots

```{r titer-noinf-3shots, fig.height=54, fig.retina=4, fig.width=18, message=FALSE, warning=FALSE, echo=FALSE}

df = df_titer %>%
  filter(dosage==3) %>%
  filter(infection=='') %>%
  filter(var_name %in% VARIANT)

plots = draw_panel_groups(df)

lines = (length(plots) %/% LINE_WIDTH) - 1
heights_ratios = rep(1, lines)
heights_ratios[length(heights_ratios) + 1] = 1.2
heights_ratios[length(heights_ratios) + 1] = 0.1

grid.arrange(grobs = plots, ncol=LINE_WIDTH, heights=heights_ratios)
```

### Titer, history of infection, 2 or more shots

```{r titer-inf-shots, fig.height=32, fig.retina=4, fig.width=18, message=FALSE, warning=FALSE, echo=FALSE}

df = df_titer %>%
  filter(dosage>=2) %>%
  filter(infection!='') %>%
  filter(var_name %in% VARIANT) %>%
  filter(!(vaccine_name %in% c('BBV152', 'Sputnik V')))

plots = draw_panel_groups(df)

lines = (length(plots) %/% LINE_WIDTH) - 1
heights_ratios = rep(1, lines)
heights_ratios[length(heights_ratios) + 1] = 1.2
heights_ratios[length(heights_ratios) + 1] = 0.1

grid.arrange(grobs = plots, ncol=LINE_WIDTH, heights=heights_ratios)
```
