---
title: "Susceptibility summary figures"
output:
  html_document:
    keep_md: yes
    css: "css/main.css"
---

Report generated at: `r format(as.POSIXct(Sys.time(), format = "%y%m%d %H:%M"), "%m/%d/%Y %I:%M %p")` PDT

```{r load-library, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(grid)
library(gridExtra)
library(plotly)
library(ggbeeswarm)
library(viridis)
library(ggpubr)
library(ggpmisc)


knitr::opts_chunk$set(
  echo = FALSE,
  dev = c("png", "svg")
)
source("./lib/readers.R", chdir = TRUE)
source("./lib/datatables.R", chdir = TRUE)

TABLEDIR = normalizePath(sprintf('%s/report_tables', .getpwd()))
```

```{r load-const, include=FALSE}
MAB_LIST = c(
    'Bamlanivimab',
    'Etesevimab',
    'Bamlanivimab/Etesevimab',
    'Casirivimab',
    'Imdevimab',
    'Casirivimab/Imdevimab',
    'Cilgavimab',
    'Tixagevimab',
    'Cilgavimab/Tixagevimab',
    'Sotrovimab',
    'Regdanvimab',
    'Adintrevimab',
    'Bebtelovimab',
    'Amubarvimab',
    'Romlusevimab',
    'Amubarvimab/Romlusevimab'
)

MAB_RENAME_LIST = c(
    'Bamlanivimab'="BAM",
    'Etesevimab'="ETE",
    'Bamlanivimab/Etesevimab'="BAM/ETE",
    'Casirivimab'="CAS",
    'Imdevimab'="IMD",
    'Casirivimab/Imdevimab'="CAS/IMD",
    'Cilgavimab'="CIL",
    'Tixagevimab'="TIX",
    'Cilgavimab/Tixagevimab'="CIL/TIX",
    'Sotrovimab'="SOT",
    'Regdanvimab'="REG",
    'Bebtelovimab'="BEB",
    'Adintrevimab'="ADG20",
    'Amubarvimab'="BRII-196",
    'Romlusevimab'="BRII-198",
    'Amubarvimab/Romlusevimab'="BRII-196/198"
)
```

```{r load-funcs, include=FALSE}

draw_omicron_mab <- function(dfPlot, figLabel, ref_labels, color_labels) {
  p <- ggplot(data=dfPlot, aes(x=category, y=y)) +
    geom_boxplot(outlier.shape=NA) +
    # geom_point(aes(color=pcolor, shape=marker), size=4) +
    geom_beeswarm(aes(colour=pcolor, shape=marker), size=8, cex = 3, method = "center") +
    scale_x_discrete(
      labels = c(
        "0" = 'WT',
        "1" = 'Omicron',
        "2" = 'Fold'
      )
    ) +
    scale_y_continuous(
      trans='log10',
      expand=expansion(mult = c(0.1, 0.1)),
      labels = trans_format("log10", math_format(10^.x)),
      limits=c(1, 10000),
      name="IC50 (ng/ml)",
      sec.axis = sec_axis(
        trans=~.,
        breaks=c(1, 10, 100, 1000, 10000),
        labels = trans_format("log10", math_format(10^.x)),
        name="Fold"
        )
    ) +
    scale_color_identity(
      labels=ref_labels,
      breaks=color_labels,
      guide=guide_legend(
        ncol=1,
        title = "References"
        )) +
    theme(
      legend.position = "none",
      legend.title = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      # plot.title = element_text(hjust = 0.5, size=12),
      
      panel.border = element_rect(fill = NA, color = 'black'),
      
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
    ) + 
    guides(shape=FALSE)
  p = p + annotate(
    "text",
    y= Inf,
    x = 1.2,
    label=figLabel,
    size=9,
    vjust=1.1
    )
  p
}
```

## Omicron mAb
```{r omicron-mab, fig.height=20, fig.retina=4, fig.width=30, message=FALSE, warning=FALSE, echo=FALSE}

df = read.dbTable('mab/omicron_mab_titer_fold_df.csv', tables_dir=TABLEDIR) %>%
  mutate(pcolor=paste("#", toupper(c), sep="")) %>%
  mutate(category=ifelse(x==0, "WT", ifelse(x==1, "Omicron", "Fold"))) %>%
  mutate(category=factor(category, c('WT', 'Omicron', 'Fold'))) %>%
  mutate(marker=ifelse(m=="o", "circle", ifelse(m=="^", "triangle", "diamond")))

df_ref_color = df %>%
  select(ref_name, pcolor) %>%
  distinct() %>%
  arrange(ref_name)

REF_LABELS = list()
COLOR_LABELS = list()
for (row in 1:nrow(df_ref_color)) {
  ref_name <- df_ref_color[row, "ref_name"]
  pcolor <- df_ref_color[row, 'pcolor']
  REF_LABELS = append(REF_LABELS, ref_name)
  COLOR_LABELS = append(COLOR_LABELS, pcolor)
}

plots = list()
i = 1
line_width = 6

for (mab_name in MAB_LIST) {
  dfPlot = df %>%
    filter(mab==mab_name)
  p = draw_omicron_mab(dfPlot, MAB_RENAME_LIST[mab_name], REF_LABELS, COLOR_LABELS)
  
  if (i %% line_width == 1) {
    p = p + theme(
      axis.title.y.left = element_text(
        size=20, face="bold", colour = "blue", angle=90),
      axis.text.y.left = element_text(size=25, color="blue"),
      axis.line.y.left = element_line(color = "blue"),
      axis.title.y.right = element_blank(),
      axis.text.y.right = element_blank(),
      axis.ticks.y.right = element_blank()
    )
  } else if (i %% line_width == 0) {
    p = p + theme(
      axis.title.y.right = element_text(
        size=20, face="bold", colour = "red"),
      axis.text.y.right = element_text(size=25, color="red"),
      axis.line.y.right = element_line(color = "red"),
      axis.title.y.left = element_blank(),
      axis.text.y.left = element_blank(),
      axis.ticks.y.left = element_blank()
    )
  }

  if (i <= length(MAB_LIST) + 1 && i > (length(MAB_LIST) - line_width)) {
    p = p + theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(size=20, face="bold"),
    )
  } else {
    p = p + theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(size=18, face="bold", color="transparent"),
    )
  }
  plots[[i]] = p
  i = i + 1
}

dfLegend1 = df %>%
  filter(substr(ref_name, 1, 1) < "T")

p = draw_omicron_mab(dfLegend1, MAB_RENAME_LIST[mab_name], REF_LABELS, COLOR_LABELS)
p = p + theme(
  legend.position = "left",
  legend.title = element_text(size=20),
  legend.text = element_text(size=20)
  )
plots[[i]] = p
i = i + 1

dfLegend2 = df %>%
  filter(substr(ref_name, 1, 1) >= "T")

p = draw_omicron_mab(dfLegend2, MAB_RENAME_LIST[mab_name], REF_LABELS, COLOR_LABELS)
p = p + theme(
  legend.position = "left",
  legend.title = element_text(size=20),
  legend.text = element_text(size=20)
  )
plots[[i]] = p


grid.arrange(grobs = plots, p_legend, ncol=line_width, widths=c(1.2,1,1,1,1,1.2))
```

## Fold density
```{r omicron-mab-density, fig.height=10, fig.retina=4, fig.width=30, message=FALSE, warning=FALSE, echo=FALSE}

df = read.dbTable('mab/omicron_mab_titer_fold_df.csv', tables_dir=TABLEDIR) %>%
  mutate(pcolor=paste("#", toupper(c), sep="")) %>%
  mutate(category=ifelse(x==0, "WT", ifelse(x==1, "Omicron", "Fold"))) %>%
  mutate(category=factor(category, c('WT', 'Omicron', 'Fold'))) %>%
  mutate(marker=ifelse(m=="o", "circle", ifelse(m=="^", "triangle", "diamond")))

draw_omicron_mab_density = function(dfPlot, figLabel) {
p <- ggplot(data=dfPlot, aes(x=y)) +
    geom_density() +
    scale_x_continuous(
      trans='log10',
      expand=expansion(mult = c(0.1, 0.1)),
      labels = trans_format("log10", math_format(10^.x)),
      limits=c(1, 10000),
      name="Fold",
    ) +
    theme(
      legend.position = "none",
      legend.title = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      # axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      # plot.title = element_text(hjust = 0.5, size=12),
      
      panel.border = element_rect(fill = NA, color = 'black'),
      
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
    ) + 
    guides(shape=FALSE)
  p = p + annotate(
    "text",
    y= Inf,
    x = 1.2,
    label=figLabel,
    size=9,
    vjust=1.1
    )
  p
}


plots = list()
i = 1
line_width = 3

for (mab_name in MAB_LIST) {
  dfPlot = df %>%
    filter(mab==mab_name) %>%
    filter(category=="Fold")
  p = draw_omicron_mab_density(dfPlot, MAB_RENAME_LIST[mab_name])
  
  plots[[i]] = p
  i = i + 1
}

grid.arrange(grobs = plots, ncol=line_width)
```


## WT IC50 PV
```{r wt-mab-density, fig.height=20, fig.retina=4, fig.width=30, message=FALSE, warning=FALSE, echo=FALSE}

df = read.dbTable('mab/omicron_mab_titer_fold_forest_figure.csv', tables_dir=TABLEDIR) %>%
  filter(assay_group=='PV')

draw_wt_mab_density = function(dfPlot, figLabel) {
p <- ggplot(data=dfPlot, aes(x=control_var_name, y=control_ic50)) +
    geom_beeswarm(size=7, cex = 3, method = "center") +
    scale_y_continuous(
      trans='log10',
      expand=expansion(mult = c(0.1, 0.1)),
      labels = trans_format("log10", math_format(10^.x)),
      limits=c(1, 10000),
      name="IC50 (ng/ml)",
    ) +
    theme(
      legend.position = "none",
      legend.title = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_text(size=20),
      # axis.text.x = element_blank(),
      axis.text.y = element_text(size=20),
      # axis.ticks.y = element_blank(),
      # plot.title = element_text(hjust = 0.5, size=12),
      
      panel.border = element_rect(fill = NA, color = 'black'),
      
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
    ) + 
    guides(shape=FALSE)
  p = p + annotate(
    "text",
    y= Inf,
    x = 1.2,
    label=figLabel,
    size=9,
    vjust=1.1
    )
  p
}


plots = list()
i = 1
line_width = 3

for (mab_name in MAB_LIST) {
  dfPlot = df %>%
    filter(ab_name==mab_name)
  p = draw_wt_mab_density(dfPlot, MAB_RENAME_LIST[mab_name])
  
  plots[[i]] = p
  i = i + 1
}

grid.arrange(grobs = plots, ncol=line_width)
```

## WT IC50 AV
```{r wt-mab-density-authentic, fig.height=20, fig.retina=4, fig.width=30, message=FALSE, warning=FALSE, echo=FALSE}

df = read.dbTable('mab/omicron_mab_titer_fold_forest_figure.csv', tables_dir=TABLEDIR) %>%
  filter(assay_group=='AV')

plots = list()
i = 1
line_width = 3

for (mab_name in MAB_LIST) {
  dfPlot = df %>%
    filter(ab_name==mab_name)
  p = draw_wt_mab_density(dfPlot, MAB_RENAME_LIST[mab_name])
  
  plots[[i]] = p
  i = i + 1
}

grid.arrange(grobs = plots, ncol=line_width)
```