---
title: "Phenotypic figures"
output:
  html_document:
    css: "css/main.css"
---

Report generated at: `r format(as.POSIXct(Sys.time(), format = "%y%m%d %H:%M"), "%m/%d/%Y %I:%M %p")` PDT

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(gridExtra)
knitr::opts_chunk$set(echo = FALSE)
source("./lib/readers.R", chdir = TRUE)

partialResistFold = 3
resistFold = 10
dfSuscResultsMAb = read.suscResultsMAb()
dfSuscResultsCP = read.suscResultsCP(
  partialResistFold = partialResistFold,
  resistFold = resistFold
)
dfSuscResultsIP = read.suscResultsIP(
  partialResistFold = partialResistFold,
  resistFold = resistFold
)
dfSuscResultsCP$group = "CP"
dfSuscResultsIP$group = "IP"
dfSuscResultsPlasma = dplyr::bind_rows(dfSuscResultsCP, dfSuscResultsIP)

filterStrains = c("S:501Y", "B.1.1.7 Spike", "S:484K", "B.1.351 Spike")
```


## Convalescent and immune plasma

Resistance levels:

* Resistance (<span style="padding: .1rem .2rem; margin: 0 .2rem; border: 1px solid black; background-color: #146aa8; color: white;">dark blue</span>): fold > `r resistFold`
* Partial-resistance (<span style="padding: .1rem .2rem; margin: 0 .2rem; border: 1px solid black; background-color: #7fcbee; color: black;">light blue</span>): fold between `r partialResistFold` and `r resistFold`
* Susceptible (<span style="padding: .1rem .2rem; margin: 0 .2rem; border: 1px solid black; background-color: #ffffff; color: black;">white</span>): fold < `r partialResistFold`

```{r plasma-fold-fig, fig.height = 10, fig.width = 12}
shortRefRxNames = c(
  "Rees-Spear21 mild" = "Mild\nRSC",
  "Rees-Spear21 severe" = "Severe\nRSC",
  "Shen21 CP_1M" = "Shen",
  "Wang21b CP" = "WangP",
  "Wang21 BNT" = "WangZ",
  "Wang21b BNT" = "WangP",
  "Xie21 BNT 2W" = "2w\nXieX1",
  "Xie21 BNT 1M" = "1m\nXieX1",
  "Xie21b BNT" = "XieX2",
  "Shen21 Mod" = "ShenX",
  "Wang21 Mod" = "WangZ",
  "Wang21b Mod" = "WangP",
  "Hu21 1mon" = "1m\nHuJ",
  "Hu21 8mon" = "8m\nHuJ",
  "Collier21 BNT" = "CollierD",
  "Muik21 BNT" = "MuikA",
  "Wu21 Mod" = "WuK",
  "Shen21 NVV" = "ShenX",
  "Greaney21 CP" = "GreaneyAJ",
  "Liu20h CP" = "LiuZ"
)
yAxisStep = 5
longRefRxNames = names(shortRefRxNames)

dfForPlot = dfSuscResultsPlasma %>%
  filter(strain_name %in% filterStrains) %>%
  mutate(
    rx_name = ifelse(is.na(cumulative_group), rx_name, cumulative_group),
    vaccine_name = ifelse(is.na(vaccine_name), "NA", vaccine_name)
  )
dfForPlot = aggregate(
  cumulative_count ~ ref_name + rx_name + vaccine_name + strain_name + resistance_level + group,
  dfForPlot,
  FUN=sum,
  na.action = na.pass
)

resistance_levels = c(
  'resistance',
  'partial-resistance',
  'susceptible'
)

dfForPlot = dfForPlot %>%
  select(ref_name, rx_name, vaccine_name, strain_name, group) %>%
  unique %>%
  merge(
    data.frame(resistance_level = resistance_levels)
  ) %>%
  merge(
    dfForPlot,
    by = c('ref_name', 'rx_name', 'vaccine_name', 'strain_name', 'group', 'resistance_level'),
    all.x = TRUE
  ) %>%
  mutate(
    cumulative_count = ifelse(is.na(cumulative_count), 0, cumulative_count),
    resistance_level = factor(resistance_level, levels = resistance_levels),
    group = factor(
      ifelse(group == "CP", "CP", vaccine_name),
      levels = c("CP", "BNT162b2", "mRNA-1273", "NVX-CoV2373")
    ),
    ref_rx = factor(
      paste(ref_name, rx_name, sep=" "),
      levels = longRefRxNames
    )
  ) %>%
  mutate(
    ref_rx = factor(ref_rx, levels = unique(c(longRefRxNames, ref_rx)))
  )

plots = list()
i = 1

for (strain in filterStrains) {
  df = dfForPlot %>%
    filter(strain_name == strain)
  totalCount = aggregate(cbind(total_count = cumulative_count) ~ ref_rx + group, df, FUN = sum)
  maxCount = ceiling((max(totalCount$total_count)) / yAxisStep) * yAxisStep
  numItems = length(unique(df$ref_rx))
  
  plot = df %>%
    ggplot(aes(x = ref_rx, y = cumulative_count)) +
    geom_bar(
      aes(fill = resistance_level),
      size = 0.2,
      color = "#000000",
      stat = 'identity', position = 'stack', width = 0.04 * numItems) +
    facet_grid(. ~ group, scales = "free", space = "free") +
    scale_x_discrete(
      labels = Vectorize(function(x) ifelse(
        x %in% longRefRxNames,
        yes = shortRefRxNames[[x]],
        no = x
      ))
    ) +
    geom_text(
      aes(x = ref_rx, y = total_count, label = total_count),
      data = totalCount,
      size = 3,
      vjust = -0.5
    ) +
    scale_y_continuous(
      expand = c(0, 0, 0.15, 0),
      limits = c(0, maxCount),
      breaks = seq(0, maxCount, yAxisStep)
    ) +
    labs(title = strain) +
    scale_fill_manual(values = c("#146aa8", "#7fcbee", "#ffffff")) +
    theme(
      plot.title = element_text(vjust = -7),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      strip.background = element_blank(),
      strip.placement = "outside",
      panel.background = element_blank(),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      legend.position = "none",
      panel.border = element_rect(fill = NA, color = 'black')
    )
  plots[[i]] = plot
  i = i + 1
}
grid.arrange(grobs = plots, nrow = 4)
```

## Monoclonal antibodies

```{r mab-fold-fig, fig.height = 10, fig.width = 12}
filterMAbs = c(
  "Bamlanivimab", "Casirivimab", "Imdevimab", "Etesevimab",
  "Vir-7831", "C121", "C135", "C144",
  "COV2-2479", "COV2-2832",
  "CC12.1", "BD23", "C119", "P2B-2F6"
)
mAbLevels = c(
  "Bamlanivimab", "Casirivimab", "Imdevimab", "Casirivimab+\nImdevimab", "Etesevimab",
  "Vir-7831", "C121", "C135", "C144",
  "COV2-2479", "COV2-2832",
  "CC12.1", "BD23", "C119", "P2B-2F6"
)
mAbLabels = c(
  "Vir-7831" = "Vir-7831\n(S309)",
  "C121" = "C121\n(RBM 1)",
  "C135" = "C135\n(RBD-core 1)"
)
mAbHasLabels = names(mAbLabels)

dfForPlot = dfSuscResultsMAb %>%
  filter(
    Vectorize(function(x) length(setdiff(x, filterMAbs)) == 0)(ab_name) &
    strain_name %in% filterStrains
  )  %>%
  mutate(
    strain_name = factor(strain_name, levels = filterStrains),
    ab_name = factor(
      Vectorize(function(x) paste(x, collapse = "+\n"))(ab_name),
      levels = mAbLevels
    )
  ) %>%
  select(ref_name, ab_name, strain_name, fold_cmp, fold)

plots = list()
i = 1

dfForPlot %>%
  ggplot(aes(x = ab_name, y = fold)) +
  geom_bar(
    aes(fill = ref_name),
    size = 0.2,
    color = "#000000",
    stat = 'identity', position = position_dodge2(preserve = 'single'), width = 0.6) +
  geom_text(
    aes(
      y = Vectorize(function(x) min(x, 190))(fold),
      label = sprintf(
        "%s%s",
        ifelse(fold_cmp == "=", "", fold_cmp),
        formatC(fold, digits = 1, format = 'fg')
      )
    ),
    position = position_dodge2(preserve = 'single', width = 0.6),
    size = 2.5,
    vjust = -0.5
  ) +
  scale_x_discrete(labels = Vectorize(function(x) ifelse(
    x %in% mAbHasLabels,
    yes = mAbLabels[[x]],
    no = x
  ))) +
  scale_y_continuous(
    trans=scales::pseudo_log_trans(base = 10),
    expand = c(0, 0, 0.1, 0),
    breaks = c(0, 10 ^ seq(0, 10))
  ) +
  coord_cartesian(ylim = c(0, 200)) +
  facet_wrap(~ strain_name, scales = "free_x", nrow = 4) +
  theme(
    plot.title = element_text(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.background = element_blank(),
    strip.placement = "outside",
    strip.text = element_text(size = 14, hjust = 0),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(fill = NA, color = 'black')
  )
```