---
title: "Resistance data tables"
output:
  html_document:
    css: "css/main.css"
---

Report generated at: `r format(as.POSIXct(Sys.time(), format = "%y%m%d %H:%M"), "%m/%d/%Y %I:%M %p")` PDT

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(gridExtra)
knitr::opts_chunk$set(echo = FALSE)
source("./lib/readers.R", chdir = TRUE)
source("./lib/datatables.R", chdir = TRUE)


partialResistFold = 3
resistFold = 10
dfSuscResultsMAb = read.suscResultsMAb(withExcluded = TRUE)
dfSuscResultsCP = read.suscResultsCP(
  partialResistFold = partialResistFold,
  resistFold = resistFold,
  withExcluded = TRUE
)
dfSuscResultsIP = read.suscResultsIP(
  partialResistFold = partialResistFold,
  resistFold = resistFold,
  withExcluded = TRUE
)
dfSuscResultsCP$group = "CP"
dfSuscResultsIP$group = "IP"
dfSuscResultsPlasma = bind_rows(dfSuscResultsCP, dfSuscResultsIP)
dfVirusStrains = read.virusStrains() %>%
  select(strain_name, num_muts)
dfArticles = read.articles()
dfStrainMutations = read.strainMutations()

dfSuscResultsMAb = dfSuscResultsMAb %>%
  inner_join(
    dfVirusStrains,
    by = "strain_name",
    suffix = c(".susc", ".strain")
  ) %>%
  inner_join(
    dfArticles,
    by = "ref_name",
    suffix = c(".susc", ".ref")
  )

dfSuscResultsPlasma = dfSuscResultsPlasma %>%
  inner_join(
    dfVirusStrains,
    by = "strain_name",
    suffix = c(".susc", ".strain")
  ) %>%
  inner_join(
    dfArticles,
    by = "ref_name",
    suffix = c(".susc", ".ref")
  )
```
 
## Individual spike mutations / mAb neutralization

```{r phenotypes-mut-mab}

dfSuscResultsMAb %>%
  filter(num_muts == 1) %>%
  inner_join(
    dfStrainMutations,
    by = "strain_name",
    suffix = c(".susc", ".strainMut")
  ) %>%
  mutate(
    DOI = ifelse(is.na(doi), url, doi),
    mAb = Vectorize(function(x) paste0(x, collapse = "+"))(short_ab_name_with_author_target),
    FoldCmp = ifelse(fold_cmp == "=", "", fold_cmp),
    Fold = ifelse(is.na(fold), "", fold),
    Assay = ifelse(is.na(assay), "", assay),
    Include = ifelse(include, "Yes", "No")
  ) %>%
  select(
    Author = ref_name,
    DOI,
    Source = section,
    Date = date_added.susc,
    mAb,
    Position = position,
    AA = amino_acid,
    FoldCmp,
    Fold,
    Assay,
    Include
  ) %>%
  arrange(
    Author,
    Position,
    AA,
    mAb
  ) %>%
  styledDT
```

## Individual spike mutations / plasma neutralization

```{r phenotypes-mut-plasma}

dfMutPlasma = dfSuscResultsPlasma %>%
  filter(num_muts == 1) %>%
  inner_join(
    dfStrainMutations,
    by = "strain_name",
    suffix = c(".susc", ".strainMut")
  )
dfMutPlasma %>%
  mutate(
    DOI = ifelse(is.na(doi), url, doi),
    Plasma = Vectorize(function(refName, rxName, strainName, ordNum) {
      total = nrow(filter(dfMutPlasma, rx_name == rxName & ref_name == refName & strain_name == strainName))
      ifelse(
        total == 1,
        yes = rxName,
        no = sprintf(sprintf("%%s:%%0%dd", 1 + floor(log(total, 10))), rxName, ordNum)
      )
    })(ref_name, rx_name, strain_name, ordinal_number),
    Vaccine = ifelse(is.na(vaccine_name), "", vaccine_name),
    FoldCmp = ifelse(fold_cmp == "=", "", fold_cmp),
    Fold = ifelse(is.na(fold), "", fold),
    Assay = ifelse(is.na(assay), "", assay),
    Count = ifelse(cumulative_count == 1, "", cumulative_count),
    Include = ifelse(include, "Yes", "No")
  ) %>%
  select(
    Author = ref_name,
    DOI,
    Source = section,
    Date = date_added.susc,
    Plasma,
    Vaccine,
    Position = position,
    AA = amino_acid,
    FoldCmp,
    Fold,
    Level = resistance_level,
    Assay,
    Count,
    Include
  ) %>%
  arrange(
    Author,
    Position,
    AA,
    Plasma,
    Vaccine
  ) %>%
  styledDT
```

## Spike variants and mutation combinations / mAb neutralization

```{r phenotypes-strain-mab}

dfSuscResultsMAb %>%
  filter(num_muts > 1) %>%
  mutate(
    DOI = ifelse(is.na(doi), url, doi),
    mAb = Vectorize(function(x) paste0(x, collapse = "+"))(short_ab_name_with_author_target),
    FoldCmp = ifelse(fold_cmp == "=", "", fold_cmp),
    Fold = ifelse(is.na(fold), "", fold),
    Assay = ifelse(is.na(assay), "", assay),
    Include = ifelse(include, "Yes", "No")
  ) %>%
  select(
    Author = ref_name,
    DOI,
    Source = section,
    Date = date_added.susc,
    mAb,
    Strain = strain_name,
    FoldCmp,
    Fold,
    Assay,
    Include
  ) %>%
  arrange(
    Author,
    Strain,
    mAb
  ) %>%
  styledDT
```

## Spike variants and mutation combinations / plasma neutralization

```{r phenotypes-strain-plasma}

dfStrainPlasma = dfSuscResultsPlasma %>%
  filter(num_muts > 1)
dfStrainPlasma %>%
  mutate(
    DOI = ifelse(is.na(doi), url, doi),
    Plasma = Vectorize(function(refName, rxName, strainName, ordNum) {
      total = nrow(filter(dfStrainPlasma, rx_name == rxName & ref_name == refName & strain_name == strainName))
      ifelse(
        total == 1,
        yes = rxName,
        no = sprintf(sprintf("%%s:%%0%dd", 1 + floor(log(total, 10))), rxName, ordNum)
      )
    })(ref_name, rx_name, strain_name, ordinal_number),
    Vaccine = ifelse(is.na(vaccine_name), "", vaccine_name),
    FoldCmp = ifelse(fold_cmp == "=", "", fold_cmp),
    Fold = ifelse(is.na(fold), "", fold),
    Assay = ifelse(is.na(assay), "", assay),
    Count = ifelse(cumulative_count == 1, "", cumulative_count),
    Include = ifelse(include, "Yes", "No")
  ) %>%
  select(
    Author = ref_name,
    DOI,
    Source = section,
    Date = date_added.susc,
    Plasma,
    Vaccine,
    Strain = strain_name,
    FoldCmp,
    Fold,
    Level = resistance_level,
    Assay,
    Count,
    Include
  ) %>%
  arrange(
    Author,
    Strain,
    Plasma,
    Vaccine
  ) %>%
  styledDT
```

## Spike mutation Invitro selection

```{r invitro-selection}
invitroResults = read.invitroResults()
invitroResults = invitroResults %>%
  inner_join(
    dfArticles,
    by = "ref_name",
    suffix = c(".invitro", ".ref")
  )
invitroResults %>%
  mutate(
    DOI = ifelse(is.na(doi), url, doi),
    # mAb = Vectorize(function(x) paste0(x, collapse = "+"))(short_ab_name_with_author_target),
    mAb = rx_name,
    Position=position,
    AAMutation=amino_acid
  ) %>%
  select(
    Author = ref_name,
    DOI,
    Source = section,
    Date = date_added.invitro,
    mAb,
    Position,
    AAMutation
  ) %>%
  arrange(
    Author,
    mAb,
    Position,
    AAMutation
  ) %>%
  styledDT
```