MAIN_MAB = {
    'Bamlanivimab': 'BAM',
    'Etesevimab': 'ETE',
    'Bamlanivimab/Etesevimab': 'BAM/ETE',
    'Casirivimab': 'CAS',
    'Imdevimab': 'IMD',
    'Casirivimab/Imdevimab': 'CAS/IMD',
    'Cilgavimab': 'CIL',
    'Tixagevimab': 'TIX',
    'Cilgavimab/Tixagevimab': 'CIL/TIX',
    'Sotrovimab': 'SOT',
    'Regdanvimab': 'REG',
    'Adintrevimab': 'ADI',
    'Bebtelovimab': 'LY-COV1404',
    'Amubarvimab': 'BRII-196',
    'Romlusevimab': 'BRII-198',
    'Amubarvimab/Romlusevimab': 'BRII-196/198',
    'C135': 'C135',
    'C144': 'C144',
    'C135/C144': 'C135/C144',
}
