---
title: "Omicron assay analysis"
output:
  html_document:
    keep_md: yes
---

Report generated at: `r format(as.POSIXct(Sys.time(), format = "%y%m%d %H:%M"), "%m/%d/%Y %I:%M %p")` PDT


```{r load-library, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbeeswarm)
library(stringr)
library(grid)
library(gridExtra)

knitr::opts_chunk$set(
  echo = FALSE,
  dev = c("png", "svg")
)
source("./lib/readers.R", chdir = TRUE)
source("./lib/datatables.R", chdir = TRUE)

TABLEDIR = normalizePath(sprintf('%s/report_tables', .getpwd()))
df <- read.dbTable('mab/omicron_assay_analysis.csv', tables_dir=TABLEDIR) %>%
  mutate(pcolor=paste("#", toupper(color), sep=""))

```

```{r load-config, include=FALSE}


draw_plot <- function(df) {

  fp <- ggplot(df, aes(x=reorder(ref_name, order_id), y=ic50, color=pcolor)) +
    geom_beeswarm() +
    scale_y_continuous(
      trans='log10',
      expand=expansion(mult = c(0.1, 0.1)),
      labels = trans_format("log10", math_format(10^.x)),
      limits=c(1, 1000),
      name="IC50 (ng/ml)",
    ) +
    # scale_x_continuous(
    #   breaks = df$order_id
    # ) + 
    scale_color_identity(
      # guide = guide_legend()
    ) +
    theme(
      legend.position = "right",
      legend.title = element_blank(),
      legend.text = element_text(size=5),
      axis.text.x = element_text(size=10, angle=90),
      
      panel.border = element_rect(fill = NA, color = 'black'),
      
      strip.background = element_blank(),
      strip.text = element_blank(),
      panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
    ) +
    xlab("Assay ID")
  fp 
} 
```

## Figures

##
```{r bam-ete, fig.height=5, fig.retina=4, fig.width=8, message=FALSE, warning=FALSE, echo=FALSE}

draw_plot(df)

print(kruskal.test(ic50 ~ order_id, data=df))

```